/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Procesos;

import MenuPrincipal.MenuP;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ProcesosVo extends javax.swing.JFrame {
    String IdRecinto;
    String IDCandidato;
    String VotoCa;
    int totalca;
    String VotoPa;
    int totalpa;    
    
    String votosca;
    String votospa;
    
    /**
     * Creates new form ProcesosVo
     */
    public ProcesosVo() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salir = new javax.swing.JButton();
        Ejecutar = new javax.swing.JButton();
        Fecha = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Voto = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proceso Colegios");

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Ejecutar.setText("Ejecutar");
        Ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjecutarActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Candidato", "Voto Candidato", "Voto Partido"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        jLabel1.setText("Voto:");

        Voto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                VotoStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Ejecutar)
                .addGap(18, 18, 18)
                .addComponent(Salir)
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Voto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Ejecutar)
                        .addComponent(Salir)
                        .addComponent(jLabel1)
                        .addComponent(Voto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjecutarActionPerformed
        // Verificar si el JDateChooser está vacío
        if (Fecha.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha", "Error", JOptionPane.ERROR_MESSAGE);            
            return;
        }
        
        totalca = (int) Voto.getValue();
        totalpa = (int) Voto.getValue();
        
        // Obtener la fecha seleccionada del JDateChooser
        Date dateSeleccionada = Fecha.getDate();
        
        // Formatear la fecha seleccionada al formato del archivo
        SimpleDateFormat sdfArchivo = new SimpleDateFormat("dd/MM/yyyy");
        String fechaFormateada = sdfArchivo.format(dateSeleccionada);

        // Limpiar la tabla antes de mostrar nuevos resultados
        DefaultTableModel model = (DefaultTableModel) Tabla.getModel();
        model.setRowCount(0);

        buscarIdColegio(fechaFormateada);
        llenarTabla(IDCandidato, totalca, totalpa);
        Voto.setValue(0);
    }//GEN-LAST:event_EjecutarActionPerformed

    private void buscarIdColegio(String fechaFormateada) {
         System.out.println("Fecha a buscar: " + fechaFormateada);

        try (BufferedReader br = new BufferedReader(new FileReader("Archivos\\Colegio.txt"))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(",");
                if (partes.length == 3 && partes[2].equals(fechaFormateada)) {
                    // Encontramos la fecha, rellenamos los campos
                    IdRecinto = partes[0].trim();
                    System.out.println("Recinto obtenido: "+IdRecinto);
                    String IdColegio = partes[1].trim();
                    System.out.println("Fecha encontrada");                    
                    buscarIdCandidato(IdColegio.trim());
                    return; // Terminamos la búsqueda una vez encontrada la fecha
                }
            }

            // Si llegamos aquí, el id no fue encontrado
            JOptionPane.showMessageDialog(this, "Fecha no encontrada", "Error", JOptionPane.ERROR_MESSAGE);

        } 
        catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void buscarIdCandidato(String IdColegio) {
        System.out.println("ID Colegio a buscar: " + IdColegio);

        try (BufferedReader br = new BufferedReader(new FileReader("Archivos\\DetallesColegio.txt"))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(",");
                if (partes.length == 1 && partes[0].equals(IdColegio)) {
                    System.out.println("Id Colegio encontrado");
                    // Encontramos el id, rellenamos los campos
                    String IdCandidato = partes[0].trim();                    
                    buscarCandidato(IdCandidato.trim());
                    return; // Terminamos la búsqueda una vez encontrado el id
                }
            }

            // Si llegamos aquí, el id no fue encontrado
            JOptionPane.showMessageDialog(this, "Id Candidato no encontrado", "Error", JOptionPane.ERROR_MESSAGE);

        } 
        catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void buscarCandidato(String IdCandidato) {
        System.out.println("Id Candidato a buscar: " + IdCandidato);
         
        try (BufferedReader br = new BufferedReader(new FileReader("Archivos\\Candidatos.txt"))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(",");
                if (partes.length == 5 && partes[0].equals(IdCandidato)) {
                    // Encontramos la fecha, rellenamos los campos
                    String IdPartido = partes[2].trim();
                    String IdCircunscripcion = partes[3].trim();
                    votosca = partes[4].trim();
                    int voto = Integer.parseInt(votosca);
                    totalca += voto;
                    System.out.println("Votos candidato: " +totalca);
                    modificarCandidato( IdCandidato);
                    System.out.println("Id Candidato encontrado"); 
                    IDCandidato = IdCandidato.trim();
                    buscarRecinto(IdCircunscripcion.trim());
                    buscarPartido(IdPartido.trim());
                    return; // Terminamos la búsqueda una vez encontrado el candidato
                }
            }

            // Si llegamos aquí, el id no fue encontrado
            JOptionPane.showMessageDialog(this, "Id Candidato no encontrado", "Error", JOptionPane.ERROR_MESSAGE);

        } 
        catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void buscarRecinto(String IdCircunscripcion) {
         System.out.println("ID Circunscripcion a buscar: " + IdCircunscripcion);

        try (BufferedReader br = new BufferedReader(new FileReader("Archivos\\Recintos.txt"))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(",");
                if (partes.length == 4 && partes[2].equals(IdCircunscripcion)) {
                    System.out.println("Id Circunscripcion encontrada");
                    // Encontramos el id, rellenamos los campos  
                    String Idrecinto = partes[0].trim();
                    if(Idrecinto.equals(IdRecinto)){
                        System.out.println("Recinto encontrado");
                        return; // Terminamos la búsqueda una vez encontrado el id
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Los recintos no coinciden", "Error", JOptionPane.ERROR_MESSAGE);                        
                        return;
                    }
                }
            }

            // Si llegamos aquí, el id no fue encontrado
            JOptionPane.showMessageDialog(this, "Id Circunscripcion no encontrada", "Error", JOptionPane.ERROR_MESSAGE);

        } 
        catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }    
    
    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        MenuP menu = new MenuP();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void VotoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_VotoStateChanged
        int voto = (int) Voto.getValue();
        if(voto < 0){
            JOptionPane.showMessageDialog(this, "los votos deben ser positivos", "Error", JOptionPane.ERROR_MESSAGE);
            Voto.setValue(0);
        }
    }//GEN-LAST:event_VotoStateChanged
 
    private void buscarPartido(String IdPartido){
         System.out.println("ID Partido a buscar: " + IdPartido);

        try (BufferedReader br = new BufferedReader(new FileReader("Archivos\\Partidos.txt"))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(",");
                if (partes.length == 3 && partes[0].equals(IdPartido)) {
                    // Encontramos el id, rellenamos los campos
                    votospa = partes[2].trim();
                    int voto = Integer.parseInt(votospa);
                    totalpa += voto;
                    System.out.println("votos partidos: " +totalca);
                    modificarPartido(IdPartido);
                    System.out.println("Id Partido encontrado");
                    return; // Terminamos la búsqueda una vez encontrado el recinto
                }
            }

            // Si llegamos aquí, el id no fue encontrado
            JOptionPane.showMessageDialog(this, "Id Partido no encontrado", "Error", JOptionPane.ERROR_MESSAGE);

        } 
        catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }       
    }
 
    private int modificarCandidato(String IdCandidato) {
        // Crear una lista para almacenar las líneas modificadas
        List<String> lineasModificadas = new ArrayList<>();

        try (BufferedReader br = new BufferedReader(new FileReader("Archivos\\Candidatos.txt"))) {
            String linea;
            boolean candidatoModificado = false;

            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(",");
                if (partes.length == 5 && partes[0].equals(IdCandidato)) {
                    String VotoCa = String.valueOf(totalca);
                    partes[4] = VotoCa;

                    // Agregamos la línea modificada a la lista
                    lineasModificadas.add(String.join(",", partes));
                    candidatoModificado = true;
                } 
                else {
                    // Si no es el usuario que estamos buscando, simplemente agregamos la línea al listado
                    lineasModificadas.add(linea);
                }
            }

            if (candidatoModificado) {
                // Ahora escribimos las líneas modificadas de vuelta al archivo
                try (BufferedWriter bw = new BufferedWriter(new FileWriter("Archivos\\Candidatos.txt"))) {
                    for (String lineaModificada : lineasModificadas) {
                        bw.write(lineaModificada);
                     bw.newLine(); // Agregamos un salto de línea después de cada línea
                        System.out.println("Votos candidato modificado en el archivo");
                    }
                }
            }

        return totalca;

        } 
        catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error al leer el archivo " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        return 0;
    }    
    
     private int modificarPartido(String IdPartido) {
        // Crear una lista para almacenar las líneas modificadas
        List<String> lineasModificadas = new ArrayList<>();

        try (BufferedReader br = new BufferedReader(new FileReader("Archivos\\Partidos.txt"))) {
            String linea;
            boolean partidoModificado = false;

            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(",");
                if (partes.length == 3 && partes[0].equals(IdPartido)) {
                    // Encontramos el partido, rellenamos los campos
                    String VotoPa = String.valueOf(totalpa);         
                    partes[2] = VotoPa;

                     // Agregamos la línea modificada a la lista
                    lineasModificadas.add(String.join(",", partes));
                    partidoModificado = true;
                } 
                else {
                    // Si no es el partido que estamos buscando, simplemente agregamos la línea al listado
                    lineasModificadas.add(linea);
                }
            }

            if (partidoModificado) {
                // Ahora escribimos las líneas modificadas de vuelta al archivo
                try (BufferedWriter bw = new BufferedWriter(new FileWriter("Archivos\\Partidos.txt"))) {
                    for (String lineaModificada : lineasModificadas) {
                        bw.write(lineaModificada);
                        bw.newLine(); // Agregamos un salto de línea después de cada línea
                        System.out.println("Votos partido modificado en el archivo");                        
                    }
                }
            }

            return totalca;

        } 
        catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error al leer el archivo " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        return 0;
    }

    private void llenarTabla(String IDCandidato, int totalca, int totalpa) {
        DefaultTableModel model = (DefaultTableModel) Tabla.getModel();
        model.addRow(new Object[]{IDCandidato, totalca, totalpa});
    }   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProcesosVo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProcesosVo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProcesosVo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProcesosVo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcesosVo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ejecutar;
    private com.toedter.calendar.JDateChooser Fecha;
    private javax.swing.JButton Salir;
    private javax.swing.JTable Tabla;
    private javax.swing.JSpinner Voto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
