/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Procesos;

import MenuPrincipal.MenuP;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ProcesosVo extends javax.swing.JFrame {

    /**
     * Creates new form ProcesosVo
     */
    public ProcesosVo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salir = new javax.swing.JButton();
        Ejecutar = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Ejecutar.setText("Ejecutar");
        Ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjecutarActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Partido", "Votos Candidato"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Ejecutar)
                .addGap(18, 18, 18)
                .addComponent(Salir)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Ejecutar)
                        .addComponent(Salir)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjecutarActionPerformed
    // Obtener la fecha seleccionada del JDateChooser
    Date fechaSeleccionada = jDateChooser1.getDate();

    // Formatear la fecha en el formato deseado (por ejemplo, "dd-MM-yyyy")
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    String fechaFormateada = sdf.format(fechaSeleccionada);

    // Crear un modelo de tabla para almacenar los datos
    DefaultTableModel modeloTabla = new DefaultTableModel();
    modeloTabla.addColumn("ID");
    modeloTabla.addColumn("Nombre");
    modeloTabla.addColumn("Partido");
    modeloTabla.addColumn("Votos Candidato");

    // Leer el archivo "Colegio" y buscar la información relacionada con la fecha
    try (BufferedReader brColegio = new BufferedReader(new FileReader("Archivos\\Colegio.txt"))) {
        String lineaColegio;
        while ((lineaColegio = brColegio.readLine()) != null) {
            // Supongamos que cada línea tiene el formato "fecha|ID"
            String[] partesColegio = lineaColegio.split(",");

            // Comparar la fecha en el archivo "Colegio" con la fecha seleccionada
            if (partesColegio.length == 2 && partesColegio[0].equals(fechaFormateada)) {
                // Obtener el ID del colegio
                String idColegio = partesColegio[1];

                // Leer el archivo "Detalle_Colegio" y buscar información relacionada con el ID del colegio
                try (BufferedReader brDetalleColegio = new BufferedReader(new FileReader("Archivos\\Detalle_Colegio.txt"))) {
                    String lineaDetalleColegio;
                    while ((lineaDetalleColegio = brDetalleColegio.readLine()) != null) {
                        // Supongamos que cada línea tiene el formato "ID|Nombre|Partido|Votos"
                        String[] partesDetalleColegio = lineaDetalleColegio.split(",");

                        // Comparar el ID del colegio en "Detalle_Colegio" con el ID obtenido de "Colegio"
                        if (partesDetalleColegio.length == 4 && partesDetalleColegio[0].equals(idColegio)) {
                            // Agregar la fila al modelo de la tabla
                            modeloTabla.addRow(new String[]{idColegio, partesDetalleColegio[1], partesDetalleColegio[2], partesDetalleColegio[3]});
                        }
                    }
                } catch (IOException e) {
                    e.printStackTrace();
                    // Manejo de errores para la lectura del archivo "Detalle_Colegio"
                    JOptionPane.showMessageDialog(this, "Error al leer el archivo 'Detalle_Colegio'", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    } catch (IOException e) {
        e.printStackTrace();
        // Manejo de errores para la lectura del archivo "Colegio"
        JOptionPane.showMessageDialog(this, "Error al leer el archivo 'Colegio'", "Error", JOptionPane.ERROR_MESSAGE);
    }

    // Establecer el modelo de la tabla con los datos encontrados
    Tabla.setModel(modeloTabla);
    }//GEN-LAST:event_EjecutarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        MenuP menu = new MenuP();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProcesosVo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProcesosVo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProcesosVo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProcesosVo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcesosVo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ejecutar;
    private javax.swing.JButton Salir;
    private javax.swing.JTable Tabla;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
