/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mantenimientos;

import MenuPrincipal.MenuP;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class DeAlianza extends javax.swing.JFrame {

    /**
     * Creates new form DeAlianza
     */
    public DeAlianza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        Id = new javax.swing.JTextField();
        IdMu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        Texto1 = new javax.swing.JLabel();
        Texto2 = new javax.swing.JLabel();
        Texto3 = new javax.swing.JLabel();
        Aliado1 = new javax.swing.JTextField();
        Aliado3 = new javax.swing.JTextField();
        Texto4 = new javax.swing.JLabel();
        Texto5 = new javax.swing.JLabel();
        Texto6 = new javax.swing.JLabel();
        Aliado6 = new javax.swing.JTextField();
        Aliado4 = new javax.swing.JTextField();
        Aliado2 = new javax.swing.JTextField();
        Aliado5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Mantenimientos de alianza");

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jLabel2.setText("Id ");

        jLabel3.setText("Id municipio");

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Texto1.setText("Aliado 1:");

        Texto2.setText("Aliado 2:");

        Texto3.setText("Aliado 3:");

        Texto4.setText("Aliado 4:");

        Texto5.setText("Aliado 5:");

        Texto6.setText("Aliado 6:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                                        .addComponent(IdMu, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Buscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Texto1)
                                        .addGap(18, 18, 18)
                                        .addComponent(Aliado1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Texto2)
                                        .addGap(18, 18, 18)
                                        .addComponent(Aliado2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Texto3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Aliado3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Texto4)
                                        .addGap(18, 18, 18)
                                        .addComponent(Aliado4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Texto5)
                                        .addGap(18, 18, 18)
                                        .addComponent(Aliado5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Texto6)
                                        .addGap(18, 18, 18)
                                        .addComponent(Aliado6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Guardar)
                        .addGap(65, 65, 65)
                        .addComponent(Limpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)))
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(IdMu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Texto1)
                            .addComponent(Aliado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Texto2)
                            .addComponent(Aliado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Texto3)
                            .addComponent(Aliado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Texto4)
                            .addComponent(Aliado4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Texto5)
                            .addComponent(Aliado5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Texto6)
                            .addComponent(Aliado6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(Limpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Salir)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        LimpiarCampos();
    }//GEN-LAST:event_LimpiarActionPerformed

    private void LimpiarCampos(){
        Id.setText("");
        IdMu.setText("");
        Aliado1.setText("");
        Aliado2.setText("");
        Aliado3.setText("");
        Aliado4.setText("");
        Aliado5.setText("");
        Aliado6.setText("");
    }
    
    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        MenuP Menu = new MenuP();
        Menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        buscarYRellenarAlianza();
    }//GEN-LAST:event_BuscarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        String id = Id.getText();
        String idmu = IdMu.getText();
        String ali1 = Aliado1.getText();
        String ali2 = Aliado2.getText();        
        String ali3 = Aliado3.getText();        
        String ali4 = Aliado4.getText();        
        String ali5 = Aliado5.getText();        
        String ali6 = Aliado6.getText();        
                        
        // Validar que el id y la descripcion no estén vacíos
        if (id.isEmpty() || idmu.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Detener el proceso
        }
        
        if(ali1.isEmpty()){
            ali1 = "-";
        }
        if(ali2.isEmpty()){
            ali2 = "-";
        }
        if(ali3.isEmpty()){
            ali3 = "-";
        }
        if(ali4.isEmpty()){
            ali4 = "-";
        }
        if(ali5.isEmpty()){
            ali5 = "-";
        }
        if(ali6.isEmpty()){
            ali6 = "-";
        }
   
        try {
            // Intentar abrir el archivo
            File archivo = new File("Archivos\\Alianzas.txt");

            // Verificar si el archivo existe
            if (archivo.exists()) {
                // Verificar si la circunscripcion ya existe en el archivo
                if (modificarAlianza(id, idmu, ali1, ali2, ali3, ali4, ali5, ali6)) {
                    JOptionPane.showMessageDialog(null, "Información de la alianza modificada en el archivo.", "Información", JOptionPane.INFORMATION_MESSAGE);
                    LimpiarCampos();
                    return; // Detener el proceso si la alianza ya existe y fue modificado
                }
            }
            else {
                // Si el archivo no existe, intentar crear uno nuevo
                if (archivo.createNewFile()) {
                    System.out.println("Se ha creado un nuevo archivo.");
                }
                else {
                    JOptionPane.showMessageDialog(null, "No se pudo crear el archivo ", "Error", JOptionPane.ERROR_MESSAGE);
                    return; // Detener el proceso si no se pudo crear el archivo
                }
            }

            CrearAlianza(archivo, id, idmu, ali1, ali2, ali3, ali4, ali5, ali6);

        } catch (IOException e) {
            // Capturar y manejar la excepción en caso de error
            JOptionPane.showMessageDialog(null, "Error al manejar el archivo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_GuardarActionPerformed
    
    private void CrearAlianza(File archivo, String id, String idmu, String ali1, String ali2, String ali3, String ali4, String ali5, String ali6) throws IOException{
        // Verificar si el id existe en el archivo de municipios
        if(!buscarIdMunicipio(idmu)){
            return;
        }       
        if(!buscarNombreAliado1(ali1)){
            return;
        }
        if(!buscarNombreAliado2(ali2)){
            return;
        }
        if(!buscarNombreAliado3(ali3)){
            return;
        }
        if(!buscarNombreAliado4(ali4)){
            return;
        }
        if(!buscarNombreAliado5(ali5)){
            return;
        }
        if(!buscarNombreAliado6(ali6)){
            return;
        }
        
        // Abrir flujos de escritura
        try (FileWriter FW = new FileWriter(archivo, true);
            BufferedWriter BW = new BufferedWriter(FW)) {

            // Crear la línea formateada
            String linea = String.format("%s, %s, %s, %s, %s, %s, %s, %s", id, idmu,ali1, ali2, ali3, ali4, ali5, ali6);
            System.out.println("Linea: " + linea);  // Agregar esta línea para imprimir la línea formateada

            // Aquí se guarda la información
            BW.write(linea);
            BW.newLine(); // Añadir una nueva línea

            JOptionPane.showMessageDialog(null, "Información guardada en el archivo.", "Información", JOptionPane.INFORMATION_MESSAGE);
            LimpiarCampos();
        }
        catch (IOException e) {
            // Capturar y manejar la excepción en caso de error
            JOptionPane.showMessageDialog(null, "Error al guardar en el archivo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }  
    }

     private boolean buscarIdMunicipio(String idmu) {
         System.out.println("ID circunscripcion a buscar: " + idmu);

        try (BufferedReader br = new BufferedReader(new FileReader("Archivos\\Municipios.txt"))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(",");
                if (partes.length == 2 && partes[0].equals(idmu)) {
                    // Encontramos el id, rellenamos los campos
                    IdMu.setText(partes[0]);
                    return true; // Terminamos la búsqueda una vez encontrado el recinto
                }
            }

            // Si llegamos aquí, el id no fue encontrado
            JOptionPane.showMessageDialog(this, "Id municipio no encontrado", "Error", JOptionPane.ERROR_MESSAGE);

        } 
        catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }
    
     private boolean buscarNombreAliado1(String ali1) {
         System.out.println("ID Partido a buscar: " + ali1);

        try (BufferedReader br = new BufferedReader(new FileReader("Archivos\\Partidos.txt"))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(",");
                if (partes.length == 3 && partes[0].equals(ali1)) {
                    // Encontramos el id, rellenamos los campos
                    return true; // Terminamos la búsqueda una vez encontrado el partido
                }
            }

            // Si llegamos aquí, el id no fue encontrado
            JOptionPane.showMessageDialog(this, "Partido no encontrado. Recuerde buscar por el ID del partido", "Error", JOptionPane.ERROR_MESSAGE);

        } 
        catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

     private boolean buscarNombreAliado2(String ali2) {
         System.out.println("ID Partido a buscar: " + ali2);

        try (BufferedReader br = new BufferedReader(new FileReader("Archivos\\Partidos.txt"))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(",");
                if (partes.length == 3 && partes[0].equals(ali2)) {
                    // Encontramos el id, rellenamos los campos
                    return true; // Terminamos la búsqueda una vez encontrado el partido
                }
            }

            // Si llegamos aquí, el id no fue encontrado
            JOptionPane.showMessageDialog(this, "Partido no encontrado. Recuerde buscar por el ID del partido", "Error", JOptionPane.ERROR_MESSAGE);

        } 
        catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

     private boolean buscarNombreAliado3(String ali3) {
         System.out.println("ID Partido a buscar: " + ali3);

        try (BufferedReader br = new BufferedReader(new FileReader("Archivos\\Partidos.txt"))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(",");
                if (partes.length == 3 && partes[0].equals(ali3)) {
                    // Encontramos el id, rellenamos los campos
                    return true; // Terminamos la búsqueda una vez encontrado el partido
                }
            }

            // Si llegamos aquí, el id no fue encontrado
            JOptionPane.showMessageDialog(this, "Partido no encontrado. Recuerde buscar por el ID del partido", "Error", JOptionPane.ERROR_MESSAGE);

        } 
        catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

     private boolean buscarNombreAliado4(String ali4) {
         System.out.println("ID Partido a buscar: " + ali4);

        try (BufferedReader br = new BufferedReader(new FileReader("Archivos\\Partidos.txt"))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(",");
                if (partes.length == 3 && partes[0].equals(ali4)) {
                    // Encontramos el id, rellenamos los campos
                    return true; // Terminamos la búsqueda una vez encontrado el partido
                }
            }

            // Si llegamos aquí, el id no fue encontrado
            JOptionPane.showMessageDialog(this, "Partido no encontrado. Recuerde buscar por el ID del partido", "Error", JOptionPane.ERROR_MESSAGE);

        } 
        catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

     private boolean buscarNombreAliado5(String ali5) {
         System.out.println("ID Partido a buscar: " + ali5);

        try (BufferedReader br = new BufferedReader(new FileReader("Archivos\\Partidos.txt"))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(",");
                if (partes.length == 3 && partes[0].equals(ali5)) {
                    // Encontramos el id, rellenamos los campos
                    return true; // Terminamos la búsqueda una vez encontrado el partido
                }
            }

            // Si llegamos aquí, el id no fue encontrado
            JOptionPane.showMessageDialog(this, "Partido no encontrado. Recuerde buscar por el ID del partido", "Error", JOptionPane.ERROR_MESSAGE);

        } 
        catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

     private boolean buscarNombreAliado6(String ali6) {
         System.out.println("ID Partido a buscar: " + ali6);

        try (BufferedReader br = new BufferedReader(new FileReader("Archivos\\Partidos.txt"))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(",");
                if (partes.length == 3 && partes[0].equals(ali6)) {
                    // Encontramos el id, rellenamos los campos
                    return true; // Terminamos la búsqueda una vez encontrado el partido
                }
            }

            // Si llegamos aquí, el id no fue encontrado
            JOptionPane.showMessageDialog(this, "Partido no encontrado. Recuerde buscar por el ID del partido", "Error", JOptionPane.ERROR_MESSAGE);

        } 
        catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }
     
     private boolean modificarAlianza(String id, String idmu, String ali1, String ali2, String ali3, String ali4, String ali5, String ali6) {
        // Verificar si el id existe en el archivo de municipios
        if(!buscarIdMunicipio(idmu)){
            return false;
        }

        // Crear una lista para almacenar las líneas modificadas
        List<String> lineasModificadas = new ArrayList<>();

        try (BufferedReader br = new BufferedReader(new FileReader("Archivos\\Alianzas.txt"))) {
            String linea;
            boolean alianzaModificada = false;

            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(",");
                if (partes.length == 8 && partes[0].equals(id)) {
                    // Encontramos la circunscripcion, rellenamos los campos
                    partes[1] = idmu;
                    partes[2] = ali1;
                    partes[3] = ali2;
                    partes[4] = ali3;
                    partes[5] = ali4;
                    partes[6] = ali5;
                    partes[7] = ali6;
                    
                    // Agregamos la línea modificada a la lista
                    lineasModificadas.add(String.join(",", partes));
                    alianzaModificada = true;
                } 
                else {
                    // Si no es la alianza que estamos buscando, simplemente agregamos la línea al listado
                    lineasModificadas.add(linea);
                }
            }

            if (alianzaModificada) {
                // Ahora escribimos las líneas modificadas de vuelta al archivo
                try (BufferedWriter bw = new BufferedWriter(new FileWriter("Archivos\\Alianzas.txt"))) {
                    for (String lineaModificada : lineasModificadas) {
                        bw.write(lineaModificada);
                     bw.newLine(); // Agregamos un salto de línea después de cada línea
                    }
                }
            }

        return alianzaModificada;

        } 
        catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error al leer el archivo " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    private void buscarYRellenarAlianza() {
        String id = Id.getText().trim();

        try (BufferedReader br = new BufferedReader(new FileReader("Archivos\\Alianzas.txt"))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(",");
                if (partes.length == 8 && partes[0].equals(id)) {
                    // Encontramos la circunscripcion, rellenamos los campos
                    IdMu.setText(partes[1]);
                    Aliado1.setText(partes[2]);                                            
                    Aliado2.setText(partes[3]);                        
                    Aliado3.setText(partes[4]);                        
                    Aliado4.setText(partes[5]);                        
                    Aliado5.setText(partes[6]);                        
                    Aliado6.setText(partes[7]);                                            
                    
                    return; // Terminamos la búsqueda una vez encontrada la circunscripcion
                }
            }

            // Si llegamos aquí, la alianza no fue encontrada
            JOptionPane.showMessageDialog(this, "Alianza no encontrada", "Error", JOptionPane.ERROR_MESSAGE);

        } 
        catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeAlianza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeAlianza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeAlianza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeAlianza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeAlianza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Aliado1;
    private javax.swing.JTextField Aliado2;
    private javax.swing.JTextField Aliado3;
    private javax.swing.JTextField Aliado4;
    private javax.swing.JTextField Aliado5;
    private javax.swing.JTextField Aliado6;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField IdMu;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Texto1;
    private javax.swing.JLabel Texto2;
    private javax.swing.JLabel Texto3;
    private javax.swing.JLabel Texto4;
    private javax.swing.JLabel Texto5;
    private javax.swing.JLabel Texto6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
